# Generated by Django 5.0.1 on 2024-05-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='download_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
