# Generated by Django 5.0.1 on 2024-05-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_song_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
